```plantuml
@startuml
class main.controller.car.Car {
    -id : Int
    -model : String
    -year : Int
    -maxSpeed : Int
    -acceleration : Int
}

interface main.controller.car.ICarRentalService {
    +isOpenNow() : Boolean
    +getAvailableCars() : List<Car>
    +getCar(id : Int) : Car?
    +getCarByModel(model : String) : Car?
}

class main.controller.car.CarRentalService implements main.controller.car.ICarRentalService {
    +isOpenNow() : Boolean
    +getAvailableCars() : List<Car>
    +getCar(id : Int) : Car?
    +getCarByModel(model : String) : Car?
}

class main.controller.car.Worker {
    -name : String
    -surname : String
    -salary : Double
    -profession : String
}

class main.controller.bolt.Taxi {
    -id : String
    -phone : String
}

interface main.controller.bolt.BoltService {
    +isActive() : Boolean
    +getTaxis() : List<Taxi>
}

interface main.repository.ICarRepository {
    +getCars() : List<Car>
}

class main.repository.CarRepository implements main.repository.ICarRepository {
    +getCars() : List<Car>
}

main.controller.car.CarRentalService -- main.repository.ICarRepository
@enduml
```
