name: Auto API Docs with LLM

on:
  push:
    branches: [ "main" ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests google-generativeai

      - name: Generate docs using LLM
        run: python scripts/generate_doc.py

      - name: Upload generated docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: docs/auto-doc.md

      - name: Commit and push updated docs to main using PAT
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "Auto Docs Bot"
          git config --global user.email "autodocs@example.com"
          git add docs/auto-doc.md

          # Commit only if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "🤖 Auto-update API docs"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin main
